// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOSsJG1O9O2Q3CpgcqGLq3zRyMpJ-woEQ',
    appId: '1:299321394412:web:63b3c80e2eefa04eafd1c9',
    messagingSenderId: '299321394412',
    projectId: 'kos-pay',
    authDomain: 'kos-pay.firebaseapp.com',
    storageBucket: 'kos-pay.firebasestorage.app',
    measurementId: 'G-WX2B823TX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5j6Wx8WEwGUiMmVehe3iMHyOgGH9RLCE',
    appId: '1:299321394412:android:c16511aa58175539afd1c9',
    messagingSenderId: '299321394412',
    projectId: 'kos-pay',
    storageBucket: 'kos-pay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTO9TJpQotklpeBQQMVdq41NyPliDTMFE',
    appId: '1:299321394412:ios:e6163587bb161fadafd1c9',
    messagingSenderId: '299321394412',
    projectId: 'kos-pay',
    storageBucket: 'kos-pay.firebasestorage.app',
    iosBundleId: 'com.example.kospayDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTO9TJpQotklpeBQQMVdq41NyPliDTMFE',
    appId: '1:299321394412:ios:e6163587bb161fadafd1c9',
    messagingSenderId: '299321394412',
    projectId: 'kos-pay',
    storageBucket: 'kos-pay.firebasestorage.app',
    iosBundleId: 'com.example.kospayDart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOSsJG1O9O2Q3CpgcqGLq3zRyMpJ-woEQ',
    appId: '1:299321394412:web:2fe41a1ba1aaecb2afd1c9',
    messagingSenderId: '299321394412',
    projectId: 'kos-pay',
    authDomain: 'kos-pay.firebaseapp.com',
    storageBucket: 'kos-pay.firebasestorage.app',
    measurementId: 'G-TXNVBKQT7S',
  );

}